version: "3"

services:

  tylist:
    build: .
    ports: 
      - 7001:7001 
    container_name: TYList
    restart: always
    depends_on:
      - db

  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    container_name: db
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - ./env/db.env
volumes:
  mariadb:
